export const GET_RECIPE = 'GET_RECIPE';
export const GET_RECIPE_BEGIN = 'GET_RECIPE_BEGIN';
export const GET_RECIPE_FINISHED = 'GET_RECIPE_FINISHED';
export const GET_RECIPE_ERROR = 'GET_RECIPE_ERROR';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const CREATE_RECIPE_BEGIN = 'CREATE_RECIPE_BEGIN';
export const CREATE_RECIPE_FINISHED = 'CREATE_RECIPE_FINISHED';
export const CREATE_RECIPE_ERROR = 'CREATE_RECIPE_ERROR';

export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_BEGIN = 'ADD_RECIPE_BEGIN';
export const ADD_RECIPE_FINISHED = 'ADD_RECIPE_FINISHED';
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';

export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const REMOVE_RECIPE_BEGIN = 'REMOVE_RECIPE_BEGIN';
export const REMOVE_RECIPE_FINISHED = 'REMOVE_RECIPE_FINISHED';
export const REMOVE_RECIPE_ERROR = 'REMOVE_RECIPE_ERROR';

export const EDIT_RECIPE = 'EDIT_RECIPE';
export const EDIT_RECIPE_BEGIN = 'EDIT_RECIPE_BEGIN';
export const EDIT_RECIPE_FINISHED = 'EDIT_RECIPE_FINISHED';
export const EDIT_RECIPE_ERROR = 'EDIT_RECIPE_ERROR';
