export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_BEGIN = 'ADD_RECIPE_BEGIN';
export const ADD_RECIPE_FINISHED = 'ADD_RECIPE_FINISHED';
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR';
