export const LOAD_RECIPES_LIST = 'LOAD_RECIPES_LIST';
export const LOAD_RECIPES_LIST_BEGIN = 'LOAD_RECIPES_LIST_BEGIN';
export const LOAD_RECIPES_LIST_FINISHED = 'LOAD_RECIPES_LIST_FINISHED';
export const LOAD_RECIPES_LIST_ERROR = 'LOAD_RECIPES_LIST_ERROR';
export const CHANGE_SORT_DIRECTION = 'CHANGE_SORT_DIRECTION';
