export const SET_SHARE_AVAILABILITY = 'SET_SHARE_AVAILABILITY';
export const CHECK_SHARE_AVAILABILITY = 'CHECK_SHARE_AVAILABILITY';
export const CHECK_SHARE_AVAILABILITY_BEGIN = 'CHECK_SHARE_AVAILABILITY_BEGIN';
export const CHECK_SHARE_AVAILABILITY_ERROR = 'CHECK_SHARE_AVAILABILITY_ERROR';
export const SHARE_RECIPE_INGREDIENTS_VIA_SMS = 'SHARE_RECIPE_INGREDIENTS_VIA_SMS';
export const SHARE_RECIPE_INGREDIENTS_VIA_SMS_BEGIN =
  'SHARE_RECIPE_INGREDIENTS_VIA_SMS_BEGIN';
export const SHARE_RECIPE_INGREDIENTS_VIA_SMS_FINISHED =
  'SHARE_RECIPE_INGREDIENTS_VIA_SMS_FINISHED';
export const SHARE_RECIPE_INGREDIENTS_VIA_SMS_ERROR =
  'SHARE_RECIPE_INGREDIENTS_VIA_SMS_ERROR';
export const SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP =
  'SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP';
export const SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP_BEGIN =
  'SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP_BEGIN';
export const SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP_FINISHED =
  'SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP_FINISHED';
export const SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP_ERROR =
  'SHARE_RECIPE_INGREDIENTS_VIA_WHATS_APP_ERROR';
